import type { NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'
import styles from '../styles/Home.module.scss'

const Home: NextPage = () => {

  return (
    <div className={styles.container}>
      <Head>
        <title>Auth in NextJS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>  
      <h1 className={styles.container__h1}> HOME PAGE </h1>
        <div className={styles.container__contentbtn}>
          <button className={styles.container__button}>
            <Link href="/login">LOGIN</Link>
          </button><button className={styles.container__button}>
            <Link href="/register">REGISTER</Link>
          </button>
          <button className={styles.container__button}>
            <Link href="/detail">DETAIL</Link>
          </button>
          <button className={styles.container__button}>
            <Link href="/default">DEFAULT</Link>
          </button>
        </div>
    </div>
  )
}

export default Home
